name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Enable later when we add tests:
      #- name: Install tools for coverage and stryker
      #  run: |
      #    dotnet tool install -g dotnet-reportgenerator-globaltool
      #    dotnet tool install -g dotnet-stryker

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ./server/server.csproj

      - name: Build
        run: dotnet build ./server/server.csproj --no-restore --configuration Release
       
      # Enable later when we add tests:
      #- name: Run Stryker
      #  working-directory: ./server
      #  run: dotnet stryker
        
      - name: Generate coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: StrykerOutput

      # Add later when we add tests:
      # - name: Test
      #   run: dotnet test ./server/server.csproj --no-build --configuration Release
